workflows:
  ios-project-debug: # Workflow ID
    name: iOS Debug # Workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          BUNDLE_ID: "com.onflyer.CodemagicHomeTask" # replace with your app bundle
          XCODE_PROJECT: "CodemagicHomeTask.xcodeproj" # Replace with your xcodeproj name
          XCODE_SCHEME: "CodemagicHomeTask" # Replace with your project name
    scripts:
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO - name: Build ipa for distribution
      - name: Increment build number
        script: |
          #!/bin/sh
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
          --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
          --scheme "$XCODE_SCHEME"
    artifacts:
       - build/ios/ipa/*.ipa
       - /tmp/xcodebuild_logs/*.log
       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - salkaorama@gmail.com # Replace with your email
     
        



