workflows:
  ios-project-debug: # Workflow ID
    name: iOS Debug # Workflow name
    environment:
      xcode: latest
      vars:
          BUNDLE_ID: "com.onflyer.CodemagicHomeTask" # replace with your app bundle
          XCODE_PROJECT: "CodemagicHomeTask.xcodeproj" # Replace with your xcodeproj name
          XCODE_SCHEME: "CodemagicHomeTask" # Replace with your project name
    scripts:
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
          --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
          --scheme "$XCODE_SCHEME"
    artifacts:
       - build/ios/ipa/*.ipa
       - /tmp/xcodebuild_logs/*.log
       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
     
        



